export enum SiteConfig {
    DEFAULT_ROLE = 'DEFAULT_ROLE',
    EMAIL_DOMAINS = 'EMAIL_DOMAINS',
    ADMIN_CONTACT = 'ADMIN_CONTACT',
    MAX_EMAILS = 'MAX_EMAILS',
    EMAIL_SERVICE_ENABLED = 'EMAIL_SERVICE_ENABLED',
    RESEND_API_KEY = 'RESEND_API_KEY',
    EMAIL_ROLE_LIMITS = 'EMAIL_ROLE_LIMITS'
}
